{ ... }:

{
  rso.home.programs.ssh = {
    enable = true;

    enableDefaultConfig = false;
    matchBlocks = {
      "*" = {
        # Default values previously generated by the HomeManager SSH module's
        # default config functionality, which is now deprecated. Recommended
        # practice is to set these values here to maintain compatibility.
        forwardAgent = false;
        addKeysToAgent = "no";
        compression = false;
        serverAliveInterval = 0;
        serverAliveCountMax = 3;
        hashKnownHosts = false;
        userKnownHostsFile = "~/.ssh/known_hosts";
        controlMaster = "no";
        controlPath = "~/.ssh/master-%r@%n:%p";
        controlPersist = "no";
      };
      "*.rso.pt rso.pt" = {
        hostname = "ssh.%h";
      };
      "*.datasektionen.se" = {
        user = "rmfseo";
      };
    };
  };
}
